#!/bin/sh
# autopkgtest check: Run the installed-tests to verify glib works correctly
# This part runs tests that have been marked as opt-in due to being flaky
# on at least some architectures.
# (C) 2013 Canonical Ltd.
# (C) 2019 Collabora Ltd.

set -eu
NULL=

export DEB_ALLOW_FLAKY_TESTS=1

# Disable gvfs if it happens to be installed. We want to test the built-in
# stuff
export GIO_USE_VFS=local
export GIO_USE_VOLUME_MONITOR=unix

export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"

printf "Running as: "; id -a
printf "passwd entry: "; getent passwd "$(id -u)" || echo "(exit status $?)"
printf "group entry: "; getent group "$(id -g)" || echo "(exit status $?)"
echo "Environment:"
env | LC_ALL=C sort -u

exec dbus-run-session -- \
xvfb-run -a \
debian/tests/run-with-locales \
	--generate de_DE \
	--generate de_DE.utf8 \
	--generate de_DE@euro.utf8 \
	--generate el_GR.utf8 \
	--generate en_GB \
	--generate en_GB.utf8 \
	--generate en_US \
	--generate en_US.utf8 \
	--generate es_ES.utf8 \
	--generate fa_IR \
	--generate fa_IR.utf8 \
	--generate fr_FR.utf8 \
	--generate hr_HR.utf8 \
	--generate ja_JP.utf8 \
	--generate ja_JP.EUC-JP \
	--generate lt_LT.utf8 \
	--generate pl_PL \
	--generate pl_PL.ISO-8859-2 \
	--generate pl_PL.utf8 \
	--generate ru_RU \
	--generate ru_RU.utf8 \
	--generate sr_RS \
	--generate sr_RS@latin \
	--generate sv_SE \
	--generate sv_SE.utf8 \
	--generate tr_TR \
	--generate tr_TR.utf8 \
	--generate tt_RU \
	--generate tt_RU.utf8 \
	--generate tt_RU@iqtelif \
	-- \
gnome-desktop-testing-runner \
	glib/closure-refcount.test \
	glib/gdbus-server-auth.test \
	glib/gdbus-threading.test \
	glib/gmenumodel.test \
	glib/mainloop.test \
	glib/socket.test \
	glib/testfilemonitor.test \
	glib/timeout.test \
	glib/timer.test \
	${NULL}
